# Generated by Django 3.1.7 on 2021-03-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0007_managernits'),
    ]

    operations = [
        migrations.AddField(
            model_name='managernits',
            name='plastic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='plastic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
