# Generated by Django 3.1.7 on 2021-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0008_auto_20210312_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='agreement',
            field=models.CharField(blank=True, choices=[('GPD', 'GPD'), ('FIXED', 'FIXED')], max_length=50, null=True),
        ),
    ]
