# Generated by Django 3.1.7 on 2021-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0010_auto_20210313_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('Kompyuter Savodxonligi', 'Kompyuter Savodxonligi'), ('C++ - Dasturlash', 'C++ - Dasturlash'), ('KiberSport', 'KiberSport'), ("Mobil O'yinlar Yaratish", "Mobil O'yinlar Yaratish"), ('SMM-Social Media Marketing', 'SMM-Social Media Marketing'), ('IT-English', 'IT-English'), ('Robototexnika', 'Robototexnika'), ('Grafik Dizayn', 'Grafik Dizayn'), ('CINEMA 4D', 'CINEMA 4D'), ('Arxitektura va Dizayn', 'Arxitektura va Dizayn'), ('Backend-Dasturlash', 'Backend-Dasturlash'), ('Frontend-Dasturlash', 'Frontend-Dasturlash'), ('Python-Dasturlash', 'Python-Dasturlash'), ('Kompyuterdan Samarali Foydalanish', 'Kompyuterdan Samarali Foydalanish'), ('Android Dasturlash(JAVA,KOTLIN)', 'Android Dasturlash(JAVA,KOTLIN)')], max_length=200, verbose_name='Course'),
        ),
    ]
