# Generated by Django 3.1.7 on 2021-03-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0011_auto_20210313_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Course'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skills',
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.ManyToManyField(to='nitc.Course'),
        ),
    ]
