# Generated by Django 3.1 on 2021-03-16 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0012_auto_20210313_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='skills',
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.teacher')),
            ],
        ),
    ]
