# Generated by Django 3.1 on 2021-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0013_auto_20210316_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
