# Generated by Django 3.1 on 2021-03-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0014_auto_20210323_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
